apiVersion: apps/v1
#
kind: Deployment
metadata:
  name: minio-example-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-example
  template:
    metadata:
      labels:
        app: minio-example
    spec:
      containers:
      - name: minio-example
        image: dirkcgrunwald/minio-example:v4
        env:
          - name: MINIO_HOST
            value: "minio:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: ExternalName
  externalName: minio-proj.minio-ns.svc.cluster.local