apiVersion: v1
kind: Pod
metadata:
  #
  # This is the name that will appear in kubectl get po
  #
  name: flask
  labels:
    app: blog
spec:
  #
  # The specification is a list of attributes, one of which
  # is the list of containers
  # 
  containers:
  - name: blog
    image: dirkcgrunwald/blog:latest
    ports:
      - containerPort: 8888
    env:
      - name: FLASK_PORT
        value: "8888"
    volumeMounts:
      - mountPath: "/app/instance"
        name: blog-pv-storage
  volumes:
    - name: blog-pv-storage
      persistentVolumeClaim:
        claimName: blog-pv-claim



    
